version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masuddh-blog
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - JEKYLL_ENV=production
